apiVersion: v1
kind: Pod
spec:
  serviceAccountName: jenkins-agent

  securityContext:
    seccompProfile:
      type: Unconfined

  containers:

    - name: git
      image: alpine/git:latest
      command:
        - cat
      tty: true

    - name: buildkit-auth
      image: moby/buildkit:rootless
      command:
        - sh
        - -c
        - cat
      tty: true
      env:
        - name: BUILDKITD_FLAGS
          value: --oci-worker-no-process-sandbox
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000

    - name: buildkit-ui
      image: moby/buildkit:rootless
      command:
        - sh
        - -c
        - cat
      tty: true
      env:
        - name: BUILDKITD_FLAGS
          value: --oci-worker-no-process-sandbox
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000

    - name: buildkit-weather
      image: moby/buildkit:rootless
      command:
        - sh
        - -c
        - cat
      tty: true
      env:
        - name: BUILDKITD_FLAGS
          value: --oci-worker-no-process-sandbox
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000

    - name: kubectl
      image: alpine/k8s:1.34.0
      command:
        - cat
      tty: true
      